### ISSUE TITLE
ApcTokenStorage

### ISSUE THREAD

**Issue by fedemotta** [f3ath/appnexusclient#2]
Hi,
I am using this library but I need to store the token in APC instead of Memcached. It seems to be an easy to develop feature. What do you think about it?

Maybe I can submit a pull request with the changes if it is okay with you.

**Comment by f3ath** [comment]
Sure, feel free to submit a PR. It should be pretty straightforward - just implement F3\AppNexusClient\TokenStorage interface. Or I'll try to make it in a day or two.

**Comment by fedemotta** [comment]
PR #3 with the implementation

**Comment by fedemotta** [comment]
Closing issue with release 0.1.0.

Thank you for your help!
